### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by ccoverflow** [wang1028-yu/darpa_management#1]
There is no direction in this DARPA dataset log. After creating it as a graph, there seems to be no direction, right?
May I ask if there is any contact information to communicate with you?

**Comment by wang1028-yu** [comment]
Hello, Darpa graph is a directed graph，and darpa data log has direction. after you creating thew graph you can use a triple like (src, relation, dst) to describe edges in this graph. The direction is src to dst.
